name: PHP test

on:
  pull_request:
    paths:
      - "**.php"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10.11
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: pass
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Resolve dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Copy .env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -ppass -e "CREATE DATABASE IF NOT EXISTS testing"
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_DATABASE: testing
          DB_PASSWORD: pass
        run: vendor/bin/phpunit
